networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - salary
      - db-praym
    networks:
      - dev

  salary:
    build: salary
    ports:
      - "8080:8080"
    depends_on:
      - db-praym
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-praym:5432/praym
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=password
    networks:
      - dev

  db-praym:
    image: postgres:latest
    environment:
      POSTGRES_DB: praym
      POSTGRES_USER: login
      POSTGRES_PASSWORD: password
#    volumes:
#      - ./data:/var/lib/ewm-db/data
    ports:
      - "5430:5432"
    networks:
      - dev
